### ISSUE TITLE
Import repo bug

### ISSUE THREAD

**Issue by kukumberman** [vazgriz/ReflexSight#1]
Hello! https://i.imgur.com/N7Zws0z.jpg after importing the project, these errors appeared. There is no possibility to use your sprites and mesh. I found some information https://answers.unity.com/questions/593064/importfbx-error-corrupted-or-invalid-file.html
Can you fix it? It would be great! I want to use it in my FPS project, but I'm bad in shaders and don't undertand how to use it without example.
Cheers, Dima

**Comment by vazgriz** [comment]
Did you download the repo using [git LFS](https://git-lfs.github.com/)?

**Comment by kukumberman** [comment]
> Did you download the repo using [git LFS](https://git-lfs.github.com/)?

Nope, should I use it?

**Comment by vazgriz** [comment]
Yes, you need to use LFS.
